### ISSUE TITLE
Handle Japanese character more correctly

### ISSUE THREAD

**Issue by trinity-1686a** [withoutboats/heck#12]
The way heck handle some languages seems to be incorrect. In languages like Japanese or Chinese their is usually no spaces between words, however heck detect some between every characters.
See Plume-org/Plume#326 for more details, when using kebab-case.
(I personally don't speak Japanese nor Chinese)

**Comment by kornelski** [comment]
I can confirm. 

"ファイルを読み込み" gets converted to "ファイル-を-読-み-込-み". Word separation is an alien concept in Japanese. "読-み" is especially incorrect, as it breaks a word in two.

It would be reasonable to completely skip processing of Hiragana, Katakana and Kanji/Hanzi. For kebab-case just remove spaces.

**Comment by rj00a** [comment]
This was fixed by #45.
