### ISSUE TITLE
Consider renaming traits to `ToSnekCase`, etc

### ISSUE THREAD

**Issue by matklad** [withoutboats/heck#15]
I think the standard naming convention for one method `verb` trait is `Verb`. That is, in case of heck, I think it's more idiomatic to prepend `To` to each trait. This might be a good occasion to publish `1.0` as well :D

**Comment by jplatte** [comment]
I like this suggestion 👍🏼

I don't think it's time for 1.0 yet, but maybe that will come after 0.4.

**Comment by jplatte** [comment]
Done in 6c384d8401370167d9c6fadbac5726cae1009923.
