### ISSUE TITLE
Inconsistent usage of `CamelCase` compared to serde

### ISSUE THREAD

**Issue by repnop** [withoutboats/heck#17]
`heck`: `CamelCase` (upper camel case, what `serde` and others call `PascalCase`)
`serde`: `camelCase` (lower camel case)

Is there a desire to be consistent with serde here?

**Comment by roanutil** [comment]
It seems like adding PascalCase and making camelCase consistent with popular use would be an improvement.

**Comment by jplatte** [comment]
I think it's worth being explicit and using "lower camel case" and "upper camel case". "pascal case" can be an alias. I agree about "mixed case" though, that seems very uncommon.

**Comment by jplatte** [comment]
Done in 2dbb21fb93c0ef554065b89cbbc37a7d03bf3edb.
