### ISSUE TITLE
Consider a different word boundary rule

### ISSUE THREAD

**Issue by withoutboats** [withoutboats/heck#2]
If a series of multiple uppercase characters is followed by 1 or more lowercase letter, consider placing the word boundary before the last uppercase letter.

That is: "HELLOWorld" -> "HELLO|World" rather than "HELLOW|orld".

But if there are no lowercase characters after, the word boundary is not inserted. "HELLO_world" -> "HELLO|world" not "HELL|O|world".

**Comment by phaux** [comment]
currently it trips on names like `XMLHttpRequest` ;(

**Comment by withoutboats** [comment]
Published a new version of this which uses this more standard word boundary rule. :-) Specific test case for `XMLHttpRequest` added.
