### ISSUE TITLE
Maintainance status

### ISSUE THREAD

**Issue by SirWindfield** [withoutboats/heck#22]
Hey!

Seeing that the last commit happened on December 2018 and the repository has some new feature PRs that haven't been touched for partially 2 years: What is the maintenance status of the crate? It seems "abandoned" at this point. The last merge was the license update in the README file.

The crate is heavily used in the Rust ecosystem, with 469,000 downloads this month alone, being used in 169 crates directly and 2,767 crates transitively. It would be a shame to let the crate be. I know that new features aren't always appreciated, but new text transformations are something that fit perfectly into `heck` ;)

That being said, if your capacities are low and you can't invest the time at the moment, I'd like to offer to sort out issues and merge PRs accordingly. I already do this for `env_logger` under the @env-logger-rs organization. And that is a crate that is as much used as this one :)

A viable alternative would be to move it to an organization, allowing for easier collaboration and allows people to add new maintainers if wished.

Thanks for taking your time to read this!
/cc @withoutboats @erickt

**Comment by jplatte** [comment]
I've taken over maintenance and published v0.3.2, now working on v0.4.0.

**Comment by SirWindfield** [comment]
Glad that someone did pick it up in the end!
