### ISSUE TITLE
Forbid unsafe code

### ISSUE THREAD

**Issue by ralpha** [withoutboats/heck#23]
`heck` does not seem to use unsafe code, which is very good :)

To prevent this from ever happening, add following line to the top:
```rust
#![forbid(unsafe_code)]
```
of https://github.com/withoutboats/heck/blob/master/src/lib.rs

This will make the package green in 
https://github.com/rust-secure-code/cargo-geiger

**Comment by jplatte** [comment]
Sure, why not. Done in 894eab60062e953f58c3f716c39b8ad7ebaf71f1.
