### ISSUE TITLE
Make the unicode-segmentation dependency optional

### ISSUE THREAD

**Issue by jplatte** [withoutboats/heck#26]
This crate is being used by a number of proc macros that are exceedingly unlikely to ever see non-ascii input. It would be good if the unicode-segmentation dependency would thus be optional.

**Comment by SirWindfield** [comment]
I'd like to help out with the issue! How would the implementation look like in the case without unicode-segmentation? Just splitting at whitespace?

**Comment by jplatte** [comment]
Haven't thought this through actually. All ASCII-only test cases should continue to pass either way. I'd imagine splitting on anything that's not `[a-zA-Z0-9]` and removing empty slices should work, but not sure. If you need more help please say so and I'll allocate some time to review the existing implementation again.

**Comment by SirWindfield** [comment]
I'll give it a try at the end of the week, thanks for giving me the heads-up!

**Comment by jplatte** [comment]
@efx you had some ideas on how to improve the non-unicode version, or are those outdated? I'd love to simply close this ^^

**Comment by efx** [comment]
@efx those are outdated. thanks! We are good to close. Go for it!

**Comment by jplatte** [comment]
Released as 0.4.0.
