### ISSUE TITLE
Release 0.3.4

### ISSUE THREAD

**Issue by jplatte** [withoutboats/heck#29]
#27 is not a breaking change, so I'd like to release it as v0.3.4. This means creating a branch for v0.3.x off the "Forbid unsafe code" commit, since the one after that introduced a breaking change.

Additionally to minimize breakage when the current traits are removed in favor of methods on the `ConvertCase` trait (the more I think about it the more I like that idea), the new methods should immediately be available with the old ones being deprecated. This means that the most obvious upgrade path if one doesn't want deprecation warnings is switching everything to the new trait directly, minimizing the possibility of ambiguity errors for the method calls.

**Comment by alex** [comment]
There seems to be an 0.3.3 release on crates.io, but I don't see a version change or any other evidence of it in this repo. Is this a legit release?

**Comment by jplatte** [comment]
It's there, just not on `master`. See `v0.3.x` branch. The release fixed #32.

**Comment by alex** [comment]
Ah, this was confusing to me, since master's Cargo.toml still shows 0.3.2, so it didn't occur to me there was a seperate maintenance branch for 0.3.x. Thanks.

**Comment by jplatte** [comment]
Hi @efx, upper camel case and lower camel case are already supported, just under somewhat weird names: upper camel case is just [CamelCase](https://docs.rs/heck/0.3.3/heck/trait.CamelCase.html), lower camel case is [mixedCase](https://docs.rs/heck/0.3.3/heck/trait.MixedCase.html).

The names that you see on the latest state of the git repo will be used starting with 0.4.0, but I want to fix #26 before releasing that and this project is very low on my todo list.

**Comment by jplatte** [comment]
This didn't happen but 0.4.0 did. I don't think there's a point in having this issue, people can follow the PR if they care about it.
