### ISSUE TITLE
Unexpected conversion with numerics

### ISSUE THREAD

**Issue by danburkert** [withoutboats/heck#3]
I expected `"FIELD_NAME11".to_snake()` to return `"field_name11"`, but instead it's returning `"field_nam_e11"`.

**Comment by H2CO3** [comment]
@withoutboats What's the status of this issue?

**Comment by withoutboats** [comment]
This was fixed by #4, I'll make a new release today.

**Comment by H2CO3** [comment]
@withoutboats Great, thanks for the quick follow-up.

**Comment by danburkert** [comment]
Friendly reminder to please publish a new version.

**Comment by withoutboats** [comment]
agh I'm such a bad maintainer sorry!

**Comment by withoutboats** [comment]
Done :-) Uploaded 0.3.0

**Comment by danburkert** [comment]
No worries, thanks again!
