### ISSUE TITLE
Sentence case

### ISSUE THREAD

**Issue by kgv** [withoutboats/heck#30]
Is it possible to add sentence case?
> Sentence case is when only the first letter of the first word is capitalised.

**Comment by jplatte** [comment]
When is that useful? It seems like it would potentially downcase more things than desireable.

**Comment by kgv** [comment]
> When is that useful?

Natural language text formatting.
Sentence case [is generally equivalent to the baseline universal standard of formal English orthography](https://en.wikipedia.org/wiki/Letter_case#Sentence_case).

> It seems like it would potentially downcase more things than desireable.

I assumed that the possible solution is send [first_word](https://github.com/withoutboats/heck/blob/f48ec3e0e9daedf502d142dd8e4e45108676f91c/src/lib.rs#L87) to [with_word](https://github.com/withoutboats/heck/blob/f48ec3e0e9daedf502d142dd8e4e45108676f91c/src/lib.rs#L61) closure as argument.

Can this change lead to any problems?

**Comment by jplatte** [comment]
> Sentence case is generally equivalent to the baseline universal standard of formal English orthography.

That is right, but this library isn't really meant for formatting whole sentences. From the readme:

> Characters not within words (such as spaces, punctuations, and underscores) are not included in the output string except as they are a part of the case being converted to.

> I assumed that the possible solution is send first_word to with_word closure as argument.
>
> Can this change lead to any problems?

No, what I was talking about is a casing transformation of whole sentences downcasing too many things, e.g. abbreviations, languages / countries that should be uppercase and names.

Can you describe your use case for sentence casing in `heck`?

**Comment by kgv** [comment]
I am working with localization. I have pieces of text that can be either an independent sentence or part of a complex sentence. In the first case, their first letter should be capitalized.

Right now I am using:

```rust
let mut chars = text.chars();
chars
    .next()
    .map(char::to_uppercase)
    .into_iter()
    .flatten()
    .chain(chars)
    .collect()
```

At first glance, it seemed to me that heck is the right place for this kind of functionality. 
But now I think that it is not so.

**Comment by jplatte** [comment]
Yes, your kind use case is not really what `heck` is suitable for.
