### ISSUE TITLE
TitleCase must keep separtors

### ISSUE THREAD

**Issue by corebreaker** [withoutboats/heck#35]
The string "hello-world everyone" converted to title case should be converted to "Hello-World Everyone" according to https://titlecaseconverter.com/

[Playback](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1a07ddcd1ff55a093bec55821d92222e)

**Comment by jplatte** [comment]
From the readme:

> Characters not within words (such as spaces, punctuations, and underscores) are not included in the output string except as they are a part of the case being converted to.

> This library is a little bit opinionated (dropping punctuation, for example). If that doesn't fit your use case, I hope there is another crate that does.
