### ISSUE TITLE
Consider supporting "UPPER CASE"

### ISSUE THREAD

**Issue by nmlt** [withoutboats/heck#40]
There is already "Title Case" so it seems it would make sense to also support converting all letters to upper case and keeping the separator spaces.

**Comment by jplatte** [comment]
Can you explain what your use case is for this? I'm already not quite clear on what people use the title case conversion for.

**Comment by nmlt** [comment]
I'm using heck via strum, to convert my enum names to displayable strings. In this case I have an SQL operator enum, and would like to transform `GroupBy` to "GROUP BY".

**Comment by jplatte** [comment]
I don't really have time to maintain this crate anymore (I took over after withoutboats stopped maintaining it). I suggest looking for alternatives if what is there now doesn't suit your needs.

**Comment by Ewie21** [comment]
I can add UPPER CASE

**Comment by jplatte** [comment]
What actual use case do you have for this? Is it not filled by [`str::to_uppercase`](https://doc.rust-lang.org/std/primitive.str.html#method.to_uppercase) from std?

**Comment by Ewie21** [comment]
Word boundaries are represented as spaces in UPPER CASE, but remain unchanged in str::to_uppercase.

**Comment by jplatte** [comment]
Okay, but that only answers half of my question. What's your actual use case?

**Comment by jplatte** [comment]
Oh right, something was mentioned above. @nmlt is that code open-source? I would like to understand the context better.

**Comment by Ewie21** [comment]
I already opened a PR with the requested features

**Comment by jplatte** [comment]
I know, but I'm very hesitant about merging it. I never said I would accept a PR for it. If I were to add every casing rule imaginable, the API docs would be flooded with things most people have never heard of and will never need. There is another PR open with `dot.case` and an uppercase version of the same.

**Comment by jplatte** [comment]
I'm sorry but I think for now I'll close this. There is no obvious name for uppercase with spaces (or lowercase with spaces), and I have no reason to believe that they fill a significant use case so far. They can already be emulated with the current API (although it's not as efficient as proper support) by transforming to title case and calling `.to_lowercase()` or `.to_uppercase()` afterwards.

I'm open to reading about the mentioned use case in more detail, or reading about additional use cases. But without that, I'm not accepting PRs for this and will thus close the issue.

**Comment by nmlt** [comment]
> Oh right, something was mentioned above. @nmlt is that code open-source? I would like to understand the context better.

The code is a mess and abandoned, but here’s my use case: https://github.com/nmlt/TeeBenchWeb/blob/fb15aaf9164d2c7902a172f28703f3570e724981/common/src/commit.rs#L11

I don’t think this will convince you, because I solved the issue with the strum macros: going from en um name “GroupBy” to “GROUP BY”.

**Comment by jplatte** [comment]
The strum macros are somewhat interesting, so they *do* alread support an "uppercase" mode where there are just no spaces. That's what I meant for there not being an obvious name for this casing convention with spaces - uppercase is clearly too generic.

Anyways, if #6 is implemented this will be possible with heck. I'm not sure how strum would expose it to users though.
