### ISSUE TITLE
Plurals of abbreviations are converted from mixed/title to snake incorrectly

### ISSUE THREAD

**Issue by Arnavion** [withoutboats/heck#8]
Test cases from [here.](https://github.com/Arnavion/k8s-openapi-codegen/blob/e0d27ea1/src/main.rs#L758-L767) (I had the same problem in that code.)

```rust
extern crate heck;

use heck::SnakeCase;

fn main() {
    // Some cases of "ABc" should be converted to "abc" instead of "a_bc".
    // Mostly (always?) happens with plurals of abbreviations.

    assert_eq!("JSONSchemas".to_snake_case(), "json_schemas"); // Actual: json_schemas
    assert_eq!("externalIPs".to_snake_case(), "external_ips"); // Actual: external_i_ps
    assert_eq!("nonResourceURLs".to_snake_case(), "non_resource_urls"); // Actual: non_resource_ur_ls
    assert_eq!("serverAddressByClientCIDRs".to_snake_case(), "server_address_by_client_cidrs"); // Actual: server_address_by_client_cid_rs
    assert_eq!("targetWWNs".to_snake_case(), "target_wwns"); // Actual: target_ww_ns
}
```

**Comment by withoutboats** [comment]
I can't think of a rule that wouldn't transform `XMLHttpRequest` as `xmlhttp_request`.

**Comment by Arnavion** [comment]
Yes, it absolutely shouldn't be done for all cases of `<uppercase><lowercase>`.

I think we have to assume it only happens with plurals, so it can be limited to cases that look like `<uppercase><uppercase>s<boundary>`. But does such an English-centric rule conflict with being "unicode-aware" ?

Alternatively there could be a `enum WordSplittingOption { Default, ConsiderEnglishPlurals }` so that the caller can opt in to this behavior?

**Comment by withoutboats** [comment]
I'm not very comfortable with basing a heuristic on the grammar of a particular language. Even in English, this could get things wrong, consider words like `As` and `Is` which, if following an abbreviation, would be parsed as a pluralization of the abbreviation.

I also specifically don't want to add configuration flags to this library. This implement one, possibly opinionated, algorithm for case transformation, ensuring that every call to it (possibly across different users) will operate consistently.

My own opinion is that in capitalized cases, abbreviations should not use capitalizations internally, that is, `XMLHttpRequest` and `externalIPs` should be `XmlHttpRequest` and `externalIps`. Obviously this isn't always under your control. But its also worth noting that this library already isn't designed to "roundtrip" strings that don't follow this rule: `"XMLHttpRequest".to_snake_case().to_camel_case()` will evaluate to `"XmlHttpRequest".

**Comment by Arnavion** [comment]
Makes sense.
