### ISSUE TITLE
Please clarify if there is code that is not covered by MIT/Apache license

### ISSUE THREAD

**Issue by erickt** [withoutboats/heck#9]
Hello @withoutboats! We want to be safe, and one way to interpret the usage of "primarily" in this [section](https://github.com/withoutboats/heck#license) in the README could be that there are files that are not covered by the MIT or Apache license. Is this true? If not, could this paragraph be rephrased to make it clear that all the files are covered by these licenses? Thanks!

**Comment by withoutboats** [comment]
I don't know why it says primarily at all, that word should be removed!
